```{r datageneration, echo = FALSE, results = "hide"}

```

Question
========

Crie um gráfico de diagrama (_boxplot_), onde o eixo horizontal é a escolaridade (coluna ESC) e o eixo vertical representa a distribuição dos dados de idade de falecimento, coluna (`age`).

Solution
================

```{r solution, eval=FALSE}
library(microdatasus) 

df_sus <- fetch_datasus(year_start = 2019, 
                        year_end = 2020, 
                        uf = "RS", 
                        information_system = "SIM-DO") |>
  process_sim() |>
  dplyr::mutate(age = as.numeric(IDADEanos)) |>
  dplyr::filter(!is.na(SEXO)) |>
  dplyr::filter(!is.na(ESC)) 

p <- ggplot(df_sus , aes(x = ESC, y = age)) + 
  geom_boxplot() + 
  labs(
    title = str_glue("Distribuição de mortalidade para diferentes escolariedades"),
    subtitle = str_glue("Dados para os anos de 2019 e 2020"),
    caption = "Dados do SUS (importado com microdatasus)",
    x = "Escolaridade",
    y = "Idade de falecimento"
  ) + 
  theme_light() 

p
```



Meta-information
================
extype: string
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: "stats 01"
exshuffle: TRUE

