```{r datageneration, echo = FALSE, results = "hide"}
vdr_run_chunks <- as.logical(Sys.getenv("vdr_run_chunks"))
knitr::opts_chunk$set(eval = vdr_run_chunks)
```

Question
========

Para o gráfico anterior, use as funções do pacote `colorspace` para implementar a paleta de cores "Harmonic" do canal `color` (dados qualitativos).


Solution
================

```{r solution}
require(ggplot2)

N <- 100
vec <- rnorm(N)
df <- dplyr::tibble(
  y = vec,
  x = 1:N,
  type = sample(c("A", "B"), size = N, replace = TRUE)
  )

p <- ggplot(df, aes(x = x, y = y, 
                    color = type, 
                    label = type)) + 
  #geom_point(aes(size = x)) + 
  labs(title = "TÍTULO",
       subtitle = "SUBTÍTULO",
       caption = "CAPTION",
       x = "texto X",
       y = "texto Y") + 
  geom_line() + 
  geom_text() + 
  colorspace::scale_colour_discrete_qualitative("Harmonic")

p
```

Meta-information
================
extype: string
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: "ggplot 08"
exshuffle: TRUE

